In [15]:
import numpy as np
x=np.array([[11,12,13,14,15],[21,22,23,24,25],[31,31,33,34,35],[41,42,43,44,45],[51,52,53,54,55]])
x

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 31, 33, 34, 35],
       [41, 42, 43, 44, 45],
       [51, 52, 53, 54, 55]])

In [22]:
#取前2行
x[:2]

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [17]:
x[:]
 

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 31, 33, 34, 35],
       [41, 42, 43, 44, 45],
       [51, 52, 53, 54, 55]])

In [25]:
#取第二列
x[ : ,1]

array([12, 22, 31, 42, 52])

In [19]:
#取第0，2列
x[ : , [ 0 ,2] ]

array([[11, 13],
       [21, 23],
       [31, 33],
       [41, 43],
       [51, 53]])

In [31]:
#取0,2,3,4列
x [ : , 0 : 4]

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 31, 33, 34],
       [41, 42, 43, 44],
       [51, 52, 53, 54]])

In [32]:
#取第5列
x[ : ,4]

array([15, 25, 35, 45, 55])