In [118]:
import numpy as np
from sklearn import preprocessing
data=[[3,-1.5,2,-5.4],[0,4,-0.3,2.1],[1,3.3,-1.9,-4.3]]
np.array(data)

array([[ 3. , -1.5,  2. , -5.4],
       [ 0. ,  4. , -0.3,  2.1],
       [ 1. ,  3.3, -1.9, -4.3]])

In [80]:
data_standard=preprocessing.scale(data)
data_standard

array([[ 1.33630621, -1.40451644,  1.29110641, -0.86687558],
       [-1.06904497,  0.84543708, -0.14577008,  1.40111286],
       [-0.26726124,  0.55907936, -1.14533633, -0.53423728]])

In [102]:
np.mean(data_standard[:,0])

5.551115123125783e-17

In [103]:
np.mean(data_standard[:,1])

-1.1102230246251565e-16

In [104]:
np.mean(data_standard[:,2])

-7.401486830834377e-17

In [101]:
#axis=0代表往跨行，而axis=1代表跨列
data_standard.mean(axis=0)

array([ 5.55111512e-17, -1.11022302e-16, -7.40148683e-17, -7.40148683e-17])

In [113]:
#Returns the standard deviation of the array
data_standard.std(axis=0)

array([1., 1., 1., 1.])

In [114]:
data_0=data_standard[:,0]
data_0_mean=np.mean(data_0)
np.sqrt(((data_0 - data_0_mean) ** 2).sum() / data_0.size)


1.0

In [115]:
#Min Max Scale 按列
#(x-min())/(max()-min())
data_scale=preprocessing.MinMaxScaler(feature_range=(0,1))
data_scale.fit_transform(data)

array([[1.        , 0.        , 1.        , 0.        ],
       [0.        , 1.        , 0.41025641, 1.        ],
       [0.33333333, 0.87272727, 0.        , 0.14666667]])

In [125]:
#L1范数 各个元素之和为1
data_l1= preprocessing.normalize(data,norm="l1")
data_l1

array([[ 0.25210084, -0.12605042,  0.16806723, -0.45378151],
       [ 0.        ,  0.625     , -0.046875  ,  0.328125  ],
       [ 0.0952381 ,  0.31428571, -0.18095238, -0.40952381]])

In [128]:
np.sum(data_l1,axis=0)



0.5656337535014004

In [132]:
data_binary=preprocessing.Binarizer(threshold=3.9).transform(data)
data_binary



array([[0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.]])