In [115]:
import numpy as np

#随机生成 20 个 0-100 之间的整数
small_count=np.random.randint(0,100,20)
print(small_count)


[48 46 45 56 96 12 78  8 76 67 82 42 25 63 19 75 43 30 95 21]


In [116]:
#通过整除均匀映射到10的分箱中，每个分箱取值是0-9
#举例 68/10=6,18/10=1
mapping=np.floor_divide(small_count,10)
print(mapping)

[4 4 4 5 9 1 7 0 7 6 8 4 2 6 1 7 4 3 9 2]


In [117]:
large_count=[19,100,1000,10000,100000,1000000,99999999,22,3224]
#举例 log10(10)=1 log10(100)=2
large_mapping=np.floor(np.log10(large_count))
print(large_mapping)

[1. 2. 3. 4. 5. 6. 7. 1. 3.]


In [118]:
#分位数映射
import pandas as pd
quantile_count=[11,33,22,66,55,77]
quantile_mapping= pd.qcut(quantile_count,2,labels=False)
print("quantile count data")
print(quantile_count)
print("quantile mapping")
print(quantile_mapping)
#将一维数据转成一列矩阵
print("series")
series=pd.Series(quantile_count)
print(series)
quantile_result=series.quantile([0.1,0.2,0.3,0.4,0.5])
print("quantile result")
print(quantile_result)

# quantile_result=series.quantile([0.4])
# print("quantile result 40%")
# print(quantile_result)




quantile count data
[11, 33, 22, 66, 55, 77]
quantile mapping
[0 0 0 1 1 1]
series
0    11
1    33
2    22
3    66
4    55
5    77
dtype: int64
quantile result
0.1    16.5
0.2    22.0
0.3    27.5
0.4    33.0
0.5    44.0
dtype: float64
